export default {
    REPORT_TYPES: {
        'NA': 'Not Identified',
        'SF': 'Stellar Feature',
        'PF': 'Planetary Feature',
        'GF': 'Geological Feature',
        'VF': 'Volcanic Feature',
        'OF': 'Organic Feature',
        'SW': 'Shipwreck',
        'TS': 'Thargoid Structure',
        'GS': 'Guardian Structure',
        'AS': 'Abandoned Human Structure',
        'ME': 'Automated Mining',
    },

    REPORT_SUB_TYPES: {
        'GF': {
            'G-NA': 'Not identified',
            'G-MNT': 'Extreme Mountains',
            'G-CAN': 'Extreme Canyons',
            'G-TER': 'Extreme Terrain',
            'G-CRT': 'Crater Structure',
            'G-OTR': 'Other',
        },
        'VF': {
            'V-NA': 'Not Identified',
            'V-HM': 'Hot Magma',
            'V-VG': 'Vapour Geysers',
            'V-LG': 'Liquid Geysers',
        },
        'OF': {
            'O-NA': 'Not Identified',
            'O-BT': 'Brain Trees',
            'O-BM': 'Bark Mounds',
            'O-FG': 'Fungal Gourds',
            'O-TB': 'Thargoid Barnacles',
            'O-TW': 'Tubeworms',
        },
        'SW': {
            'SW-NA': 'Not Identified',
            'SW-HUO': 'Human Object',
            'SW-ALO': 'Alien Object',
        },
    },

    STAR_CLASS: {
        "O": "O-type main-sequence star",
        "B": "B-type main-sequence star",
        "A": "A-type main-sequence star",
        "F": "F-type main-sequence star",
        "G": "G-type main-sequence star",
        "K": "K-type main-sequence star",
        "M": "M-type main-sequence star",
        "L": "L-type dwarf",
        "T": "T-type dwarf",
        "Y": "Y-type dwarf",
        "TTS": "T Tauri star",
        "AeBe": "Herbig Ae/Be star",
        "W": "W-type Wolf–Rayet",
        "WN": "WN-type Wolf–Rayet",
        "WNC": "WNC-type Wolf–Rayet",
        "WC": "WC-type Wolf–Rayet",
        "WO": "WO-type Wolf–Rayet",
        "CS": "CS-type carbon star",
        "C": "C-type carbon star",
        "CN": "CN-type carbon star",
        "CJ": "CJ-type carbon star",
        "CH": "CH-type carbon star",
        "CHd": "CHd-type carbon star",
        "MS": "MS-type carbon star",
        "S": "S-type carbon star",
        "D": "D-type white dwarf",
        "DA": "DA-type white dwarf",
        "DAB": "DAB-type white dwarf",
        "DAO": "DAO-type white dwarf",
        "DAZ": "DAZ-type white dwarf",
        "DAV": "DAV-type white dwarf",
        "DB": "DB-type white dwarf",
        "DBZ": "DBZ-type white dwarf",
        "DBV": "DBV-type white dwarf",
        "DO": "DO-type white dwarf",
        "DOV": "DOV-type white dwarf",
        "DQ": "DQ-type white dwarf",
        "DC": "DC-type white dwarf",
        "DCV": "DCV-type white dwarf",
        "DX": "DX-type white dwarf",
        "A_BlueWhiteSuperGiant": "A-type Blue-White Super Giant",
        "F_WhiteSuperGiant": "F-type White Super Giant",
        "M_RedSuperGiant": "M-type Red Super Giant",
        "M_RedGiant": "M-type Red Giant",
        "K_OrangeGiant": "K-type Orange Giant",
        "N": "Neutron star",
        "H": "Black hole",
        "X": "Exotic star",
        "SupermassiveBlackHole": "Supermassive black hole",
        "RoguePlanet": "Rogue planet",
        "StellarRemnantNebula": "Stellar remnant nebula",
    },
    BELT_CLASS: {
        "eRingClass_Metalic": "Metalic",
        "eRingClass_MetalRich": "Metal-rich",
        "eRingClass_Rocky": "Rocky",
        "eRingClass_Icy": "Icy",
    },
    ATMOSPHERE_TYPE: {
        "CarbonDioxide": "Carbon dioxide",
        "ArgonRich": "Argon-rich",
        "SulphurDioxide": "Sulfur dioxide",
        "MethaneRich": "Methane-rich",
        "CarbonDioxidRich": "Carbon dioxide-rich",
        "SilicateVapour": "Silicate vapour",
        "WaterRich": "Water-rich",
        "NeonRich": "Neon-rich",
        "AmmoniaRich": "Ammonia-rich",
        "AmmoniaOxygen": "Ammonia and oxygen",
        "MetallicVapour": "Metallic vapour",
        "EarthLike": "Earth-like",
    },
    API_PROCESSING_MSG: {
        apirst: 'reseting api-key',
        everify: 'email verification in progress',
        passch: 'updating password',
        passrst: 'reseting password',
        poirep: 'report submission',
        record: 'journal data sync',
        signin: 'logging in',
        signup: 'creating new profile',
    }
}